version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - echo Okay to do in the pre_build phase...
  build:
    commands:
      - printenv
      - echo Build started on `date`
      # - mvn install
      - mvn package -Dwar.finalName=${CODEBUILD_BUILD_NUMBER}
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/*
    - appspec.yml
    - scripts/*